name: Sync Changes to Other Branches

on:
  push:
    branches:
      - main

jobs:
  sync-branches:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Configure Git
      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      # Step 3: Create Pull Request to dynamic-config
      - name: Cherry-pick to dynamic-config
        run: |
          git fetch origin dynamic-config
          git checkout dynamic-config
          git cherry-pick ${{ github.sha }} || (git cherry-pick --abort && echo "No changes to pick for dynamic-config")
          git push origin dynamic-config
